spring:
  config:
    activate:
      on-profile: rest
  jooq:
    sql-dialect: POSTGRES
    bind-offset-date-time-type: false
  sql:
    init:
      mode: always
      data-locations: classpath*:db/data-pg.sql
  flyway:
    enabled: true
    url: '@flyway.url@'
    user: '@flyway.user@'
    password: '@flyway.password@'
    locations: classpath:db/migration,classpath:db/specific/postgres

---
spring:
  config:
    activate:
      on-profile: solver,geo-server
  web:
    resources:
      add-mappings: false
management:
  health:
    r2dbc:
      enabled: false

---
spring:
  config:
    activate:
      on-profile: geo-server
  rsocket:
    server:
      port: 7000