spring:
  application:
    name: single-app
  jooq:
    sql-dialect: H2
    bind-offset-date-time-type: true
  sql:
    init:
      mode: always
      data-locations: classpath*:db/data-h2.sql
  flyway:
    enabled: true
    url: '@flyway.url@'
    user: '@flyway.user@'
    password: '@flyway.password@'
    locations: classpath:db/migration,classpath:db/specific/h2
