spring:
  jooq:
    sql-dialect: POSTGRES
  sql:
    init:
      mode: always
      data-locations: classpath*:db/data-pg.sql
  flyway:
    enabled: true
    locations: classpath:db/migration,classpath:db/specific/postgres