name: OptaRouter Release CI
on:
  workflow_dispatch:
  push:
    tags:
      - v*

env:
  JAVA_VERSION: '21'
  JAVA_DISTRO: 'temurin'

jobs:
  gradle_master_build:
    name: Gradle Release Task
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 0

      - uses: n1hility/cancel-previous-runs@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          cache: 'gradle'
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRO }}

      - name: Running gradle task
        uses: gradle/actions/setup-gradle@v4

      - name: Running gradle task
        run: ./gradlew clean jreleaserRelease -PenvironmentName=single
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
