name: OptaRouter Tag Release Workflow CI
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'The tag to release'
        required: true

env:
  JAVA_VERSION: '21'
  JAVA_DISTRO: 'temurin'

jobs:
  gradle_master_build:
    name: Gradle Release Task
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.tag }} # This checks out the specific tag that triggered the workflow
          fetch-depth: 0

      - uses: n1hility/cancel-previous-runs@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          cache: 'gradle'
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRO }}

      - name: Running gradle task
        uses: gradle/actions/setup-gradle@v4

      - name: Running gradle task
        run: ./gradlew clean jreleaserRelease -PenvironmentName=single --stacktrace
        env:
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
